### ISSUE TITLE
Workflow testing

### ISSUE THREAD

**Issue by Nightwarden24** [Nightwarden24/WeakAuras2#17]
### Workflow testing 

I don't know how to properly test GitHub Actions workflows. For me, the Run workflow button on the Actions tab for the `workflow_dispatch` event never appeared.

I did the following:

- to get started

1. Create a test branch
2. Create a .yml file. In it, specify the `push` event with parameters `branches` and `paths` as an event that triggers a workflow.
```yml
...
on:
  push:
    branches:
      - <your test branch>
    paths:
      - <path to any other file, committing and pushing changes to which starts a workflow>
...
```
3. Add the .yml file to your test branch

- to run

4. Modify the file whose path you specified in step 2
5. Push it to your test branch

For an alternative method with Github CLI, see answers to [this question](https://stackoverflow.com/questions/63362126) on stackoverflow. I haven't tried it.

A useful quote from the docs from my point of view, which has apparently been removed:

> If the event occurred on a particular repository branch, then the workflow files must be present in the repository on that branch.
